version: '3.7'
services:
    nginx:
        image: nginx:latest
        ports:
            - 127.0.0.1:${NGINX_PORT}:80
        volumes:
            - ./docker/logs/nginx:/var/logs/nginx
            - ./project:/var/www
            - ./docker/conf/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php-fpm
        networks:
            queue:
                aliases:
                    - queue.test
    php-fpm:
        build:
            context: ./docker/images/php-fpm
            dockerfile: Dockerfile
        ports:
            - '9000:9000'
        environment:
            WWWUSER: '${WWWUSER}'
            WWWGROUP: '${WWWGROUP}'
        volumes:
            - ${PWD}/docker/conf/php-fpm/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./project:/var/www:rw
        networks:
            - queue
        depends_on:
            - mysql
            - redis
    mysql:
        image: mysql:8.0.31
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - TZ=Europe/Moscow
        ports:
            - 127.0.0.1:${DB_PORT}:3306
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
        networks:
            - queue
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - './docker/data/redis:/data'
        networks:
            - queue

networks:
    queue:
        driver: bridge

